
/* TABLESPACE ADMIN */

/* DEFAULT */

CREATE TABLESPACE APADMINDEF 
    DATAFILE 'APADMINDEF.DBF' SIZE 2M AUTOEXTEND ON;

/* TEMPORARY */

CREATE TEMPORARY TABLESPACE APADMINTMP 
    TEMPFILE 'APADMINTMP.DBF' SIZE 2M AUTOEXTEND ON; 

    
/* CREAR USUARIO ADMIN*/

CREATE USER ADMIN IDENTIFIED BY apass
DEFAULT TABLESPACE APADMINDEF
TEMPORARY TABLESPACE APADMINTMP
QUOTA 2M ON APADMINDEF;

/* CONNECT ADMIN*/
GRANT connect,resource,dba, CREATE ROLE , ALTER ANY ROLE , DROP ANY ROLE  TO admin with admin option;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE, SELECT ANY SEQUENCE TO admin;
GRANT CREATE PUBLIC SYNONYM , DROP ANY SYNONYM , DROP PUBLIC SYNONYM  TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;
--REVOKE ANY PRIVILEGES FROM admin;

--ALTER tablespace APAL_ADMINDEF ADD datafile 'APAL_USERSDEF.DBF' size 50M;

/* TABLESPACE ADMIN */

/* DEFAULT */
CREATE TABLESPACE APUSERSDEF 
    DATAFILE 'APUSERSDEF.DBF' SIZE 2M AUTOEXTEND ON;

/* TEMPORARY */
CREATE TEMPORARY TABLESPACE APUSERSTMP 
    TEMPFILE 'APUSERSTMP.DBF' SIZE 2M AUTOEXTEND ON; 

/* CREAR USUARIO ESTUDIANTE*/

CREATE USER STUDENT IDENTIFIED BY epass
DEFAULT TABLESPACE APUSERSDEF
TEMPORARY TABLESPACE APUSERSTMP;

/* CONNECT ESTUDIANTE*/
GRANT connect TO student;


/* CREAR USUARIO CREADORUSUARIOS*/

CREATE USER CREADORUSUARIOS IDENTIFIED BY cpass
DEFAULT TABLESPACE APUSERSDEF
TEMPORARY TABLESPACE APUSERSTMP;

/* CONNECT CREADORUSUARIOS*/
GRANT connect TO creadorUsuarios;
GRANT create user to creadorUsuarios;


/* CREAR USUARIO ASISTENTE*/

CREATE USER ASISTENTE IDENTIFIED BY apass
DEFAULT TABLESPACE APUSERSDEF
TEMPORARY TABLESPACE APUSERSTMP;

/* CONNECT ASISTENTE*/
GRANT connect TO asistente;

/*
DROP USER admin CASCADE;
DROP USER student CASCADE;
DROP USER asistente CASCADE;
DROP USER creadorUsuarios CASCADE;
*/

--ALTER SESSION SET NLS_TERRITORY = 'AMERICA';
--ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';
