
/* TABLESPACE ADMIN */

/* DEFAULT */

CREATE TABLESPACE APAL_ADMINDEF 
    DATAFILE 'APAL_ADMINDEF.DBF' SIZE 2M AUTOEXTEND ON;

/* TEMPORARY */

CREATE TEMPORARY TABLESPACE APAL_ADMINTMP 
    TEMPFILE 'APAL_ADMINTMP.DBF' SIZE 2M AUTOEXTEND ON;  

    
/* CREAR USUARIO ADMIN*/

CREATE USER admin IDENTIFIED BY apass
DEFAULT TABLESPACE APAL_ADMINDEF
TEMPORARY TABLESPACE APAL_ADMINTMP
QUOTA 2M ON APAL_ADMINDEF;

/* CONNECT ADMIN*/
GRANT connect,resource, CREATE ROLE , ALTER ANY ROLE , DROP ANY ROLE  TO admin with admin option;
GRANT CREATE ANY SEQUENCE, ALTER ANY SEQUENCE, DROP ANY SEQUENCE, SELECT ANY SEQUENCE TO admin;
GRANT CREATE PUBLIC SYNONYM , DROP ANY SYNONYM , DROP PUBLIC SYNONYM  TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;
--REVOKE ANY PRIVILEGES FROM admin;

/* TABLESPACE USERS */

/* DEFAULT */

CREATE TABLESPACE APAL_USERSDEF 
    DATAFILE 'APAL_USERSDEF.DBF' SIZE 2M AUTOEXTEND ON;

/* TEMPORARY */

CREATE TEMPORARY TABLESPACE APAL_USERSTMP
    TEMPFILE 'APAL_USERSTMP.DBF' SIZE 2M AUTOEXTEND ON;


/* CREAR USUARIO ESTUDIANTE*/

CREATE USER estudiante IDENTIFIED BY epass
DEFAULT TABLESPACE APAL_USERSDEF
TEMPORARY TABLESPACE APAL_USERSTMP
QUOTA 2M ON APAL_USERSDEF;

/* CONNECT ESTUDIANTE*/
GRANT connect TO estudiante;


/* CREAR USUARIO CREADORUSUARIOS*/

CREATE USER creadorUsuarios IDENTIFIED BY apass
DEFAULT TABLESPACE APAL_USERSDEF
TEMPORARY TABLESPACE APAL_USERSTMP
QUOTA 2M ON APAL_USERSDEF;

/* CONNECT CREADORUSUARIOS*/
GRANT connect TO creadorUsuarios;
GRANT create user to creadorUsuarios;


/* CREAR USUARIO ASISTENTE*/

CREATE USER asistente IDENTIFIED BY apass
DEFAULT TABLESPACE APAL_USERSDEF
TEMPORARY TABLESPACE APAL_USERSTMP
QUOTA 2M ON APAL_USERSDEF;

/* CONNECT ASISTENTE*/
GRANT connect TO asistente;

/*
DROP USER admin CASCADE;
DROP USER estudiante CASCADE;
DROP USER asistente CASCADE;
DROP USER creadorUsuarios CASCADE;
*/

ALTER SESSION SET NLS_TERRITORY = 'AMERICA';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';
