
/* TABLESPACE */
/* DEFAULT */

CREATE TABLESPACE APALDEF 
    DATAFILE 'APALDEF.DBF' SIZE 2M AUTOEXTEND ON;

/* TEMPORARY */

CREATE TEMPORARY TABLESPACE APALTMP 
    TEMPFILE 'APALTMP.DBF' SIZE 2M AUTOEXTEND ON;  
    
/* CREAR USUARIO BASE*/

CREATE USER APAL IDENTIFIED BY apal
DEFAULT TABLESPACE APALDEF
TEMPORARY TABLESPACE APALTMP
QUOTA 2M ON APALDEF
PASSWORD EXPIRE;

GRANT connect, resource TO APAL;

-- GRANT dba TO APAL WITH ADMIN OPTION;
